name: Daily Test
on:
  schedule:
    - cron:  '0 12 * * *'
  push:
    branches: [ main ]
    paths:
     - 'Setup-LeagueClient.ps1'
  pull_request:
    branches: [ main ]
    paths:
     - 'Setup-LeagueClient.ps1'
  workflow_dispatch:
jobs:
  install:
    name: Test the action
    runs-on: windows-latest
    steps:

      - name: Setup the League Client
        uses: mikaeldui/setup-league-client@main
        with:
          username: ${{ secrets.LOL_USERNAME }}
          password: ${{ secrets.LOL_PASSWORD }}
          region: ${{ secrets.LOL_REGION }}
