name: Development Branches
on:
  schedule:
    - cron:  '0 12 * * *'
  push:
    branches-ignore: [ main ]
    paths:
     - 'Windows/Setup-LeagueClient.ps1'
  pull_request:
    paths:
     - 'Windows/Setup-LeagueClient.ps1'
  workflow_dispatch:
concurrency: lol
jobs:
  install:
    name: Test the action
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup the League Client
        id: league-client
        uses: ./
        with:
          username: ${{ secrets.LOL_USERNAME }}
          password: ${{ secrets.LOL_PASSWORD }}
          region: ${{ secrets.LOL_REGION }}
          
      - name: Test outputs
        uses: actions/github-script@v5
        with:
          script: |
            "${{ steps.league-client.outputs.lcu-password }}".length === 0 && core.setFailed("No LCU Password Output");
            "${{ steps.league-client.outputs.lcu-port }}".length === 0 && core.setFailed("No LCU Port Output");
            "${{ steps.league-client.outputs.lcu-directory }}".length === 0 && core.setFailed("No LCU Directory Output");
